name: Generate D2 Architecture Diagram

on:
  push:
    paths:
      - 'architecture.d2'

jobs:
  render-diagram:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install D2 CLI
        run: |
          curl -fsSL https://d2lang.com/install.sh | sh -s --
          echo "$HOME/.d2/bin" >> $GITHUB_PATH

      - name: Render diagram to PNG
        run: |
          ~/.d2/bin/d2 architecture.d2 architecture.png

      - name: Upload diagram as artifact
        uses: actions/upload-artifact@v3
        with:
          name: architecture-diagram
          path: architecture.png
